"""Day 33: Add user settings fields

Revision ID: 2e79b5859acc
Revises: 9252ba1228fa
Create Date: 2026-07-22 13:06:40.999618

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "2e79b5859acc"
down_revision = "9252ba1228fa"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - adjusted ###

    with op.batch_alter_table("users", schema=None) as batch_op:

        batch_op.add_column(
            sa.Column(
                "timezone",
                sa.String(length=100),
                nullable=False,
                server_default="Asia/Kolkata"
            )
        )

        batch_op.add_column(
            sa.Column(
                "webhook_url",
                sa.String(length=500),
                nullable=True
            )
        )

        # Remove the temporary default after existing rows are populated
        batch_op.alter_column(
            "timezone",
            server_default=None
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - adjusted ###

    with op.batch_alter_table("users", schema=None) as batch_op:

        batch_op.drop_column("webhook_url")

        batch_op.drop_column("timezone")

    # ### end Alembic commands ###